[project]
name = "aa84-ai"
version = "0.1.0"
description = "AWS Lambda function"
requires-python = "3.13"
dependencies = [
    "boto3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = []