AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: OpenAI Lambda Function

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  OcrDetectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ocr-detector
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
    Metadata:
      BuildMethod: python3.13
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: post

Parameters:
  OpenAIApiKey:
    Type: String
    Description: OpenAI API Key
    NoEcho: true

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"