name: Deploy to Azure Container Registry

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Azure Login with Service Principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      env:
        ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        IMAGE_NAME: aa84-ai
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG .
        docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest .
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest
    
    - name: Deploy to Azure Container Instances
      if: ${{ secrets.DEPLOY_TO_ACI == 'true' }}
      run: |
        az container create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --name aa84-ai-container \
          --image ${{ secrets.ACR_LOGIN_SERVER }}/aa84-ai:${{ github.sha }} \
          --cpu 1 \
          --memory 1 \
          --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --dns-name-label aa84-ai-${{ github.run_number }} \
          --ports 8000 \
          --environment-variables OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"